In [1]:
import pandas as pd
import numpy as np
veriler =pd.read_csv('play_tennis.csv')

In [2]:
veriler.head()

    outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

In [3]:
#outlook sütunu kategorik olduğu için onu makinenin anlayacağı dile çevireceğiz.

outlookSütunu = veriler.iloc[:,0:1].values
outlookSütunu

array([['sunny'],
       ['sunny'],
       ['overcast'],
       ['rainy'],
       ['rainy'],
       ['rainy'],
       ['overcast'],
       ['sunny'],
       ['sunny'],
       ['rainy'],
       ['sunny'],
       ['overcast'],
       ['overcast'],
       ['rainy']], dtype=object)

In [4]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
outlookSütunu[:,0] = le.fit_transform(veriler.iloc[:,0])
#fit -> kaç farklı kategori var öğren.
#transform -> şimdi bunları sayıya çevir.
outlookSütunu

ohe = preprocessing.OneHotEncoder()
outlookSütunları=ohe.fit_transform(outlookSütunu).toarray() 
outlookSütunları

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [5]:
outlookSonuc = pd.DataFrame(data=outlookSütunları,index=range(14),columns=['overcast','rainy','sunny'])
outlookSonuc

    overcast  rainy  sunny
0        0.0    0.0    1.0
1        0.0    0.0    1.0
2        1.0    0.0    0.0
3        0.0    1.0    0.0
4        0.0    1.0    0.0
5        0.0    1.0    0.0
6        1.0    0.0    0.0
7        0.0    0.0    1.0
8        0.0    0.0    1.0
9        0.0    1.0    0.0
10       0.0    0.0    1.0
11       1.0    0.0    0.0
12       1.0    0.0    0.0
13       0.0    1.0    0.0

In [6]:
#windy sütunu boolean olduğu için onu da makinenin anlayacağı dile çevireceğiz

windySütunu = veriler.iloc[:,3:4].astype(int).values
le = preprocessing.LabelEncoder()
windySütunu[:,0] = le.fit_transform(veriler.iloc[:,3])
windySütunu


windySonuc = pd.DataFrame(data=windySütunu,index=range(14),columns=['windy'])
windySonuc

    windy
0       0
1       1
2       0
3       0
4       0
5       1
6       1
7       0
8       0
9       0
10      1
11      1
12      0
13      1

In [7]:
#play sütunu makineye öğretmek istediğimiz sütun, bunun için sadece labelEncoder yapıcaz.

playSütunu= veriler.iloc[:,4:5].values

le = preprocessing.LabelEncoder()
playSütunu[:,0]= le.fit_transform(veriler.iloc[:,4:5])
playSonuc=playSütunu
playSonuc

C:\Users\Görkem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]], dtype=object)

In [8]:
#datasetteki sayısal sütunları da çekiyoruz
#1 ve 2.indeksler

sayisalSütunlar = veriler.iloc[:,[1,2]]
sayisalSütunlar

    temperature  humidity
0            85        85
1            80        90
2            83        86
3            70        96
4            68        80
5            65        70
6            64        65
7            72        95
8            69        70
9            75        80
10           75        70
11           72        90
12           81        75
13           71        91

In [9]:
concatted_df = pd.concat([outlookSonuc,windySonuc,sayisalSütunlar],axis=1)
#axis= 1 yaapmamızın sebebi yan yana birleştirmek istememiz
concatted_df

    overcast  rainy  sunny  windy  temperature  humidity
0        0.0    0.0    1.0      0           85        85
1        0.0    0.0    1.0      1           80        90
2        1.0    0.0    0.0      0           83        86
3        0.0    1.0    0.0      0           70        96
4        0.0    1.0    0.0      0           68        80
5        0.0    1.0    0.0      1           65        70
6        1.0    0.0    0.0      1           64        65
7        0.0    0.0    1.0      0           72        95
8        0.0    0.0    1.0      0           69        70
9        0.0    1.0    0.0      0           75        80
10       0.0    0.0    1.0      1           75        70
11       1.0    0.0    0.0      1           72        90
12       1.0    0.0    0.0      0           81        75
13       0.0    1.0    0.0      1           71        91

In [10]:
concatted_df = concatted_df.drop('overcast',axis=1)
#axis=1 burada sütun sildiğimizi belirtiyor.
concatted_df

    rainy  sunny  windy  temperature  humidity
0     0.0    1.0      0           85        85
1     0.0    1.0      1           80        90
2     0.0    0.0      0           83        86
3     1.0    0.0      0           70        96
4     1.0    0.0      0           68        80
5     1.0    0.0      1           65        70
6     0.0    0.0      1           64        65
7     0.0    1.0      0           72        95
8     0.0    1.0      0           69        70
9     1.0    0.0      0           75        80
10    0.0    1.0      1           75        70
11    0.0    0.0      1           72        90
12    0.0    0.0      0           81        75
13    1.0    0.0      1           71        91

In [11]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(concatted_df,playSonuc,test_size=0.33,random_state=0)

#makineye eğitim verilerini verdik, henüz eğitmedik

In [12]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

regressor.fit(x_train,y_train)
#makineye eğitim verilerini verdim

LinearRegression()

In [13]:
#tahmin etme bölümü

y_pred=regressor.predict(x_test)
y_pred

array([[0.74233631],
       [0.75371988],
       [0.78998557],
       [0.27181229],
       [0.78572451]])

In [14]:
import statsmodels.api as sm

#statsmodels kütüphanesi bizden tek başına 1'lerden oluşan bir sütun eklememizi ister.
birler = np.append(arr=np.ones((14,1)).astype(int),values=concatted_df,axis=1)
X= birler
X

array([[ 1.,  0.,  1.,  0., 85., 85.],
       [ 1.,  0.,  1.,  1., 80., 90.],
       [ 1.,  0.,  0.,  0., 83., 86.],
       [ 1.,  1.,  0.,  0., 70., 96.],
       [ 1.,  1.,  0.,  0., 68., 80.],
       [ 1.,  1.,  0.,  1., 65., 70.],
       [ 1.,  0.,  0.,  1., 64., 65.],
       [ 1.,  0.,  1.,  0., 72., 95.],
       [ 1.,  0.,  1.,  0., 69., 70.],
       [ 1.,  1.,  0.,  0., 75., 80.],
       [ 1.,  0.,  1.,  1., 75., 70.],
       [ 1.,  0.,  0.,  1., 72., 90.],
       [ 1.,  0.,  0.,  0., 81., 75.],
       [ 1.,  1.,  0.,  1., 71., 91.]])

In [15]:
#Tüm sütunları listeye aldık
X_liste = np.array(X[:,[0,1,2,3,4,5]],dtype=float)

#modeli kurup bize rapor ver diyoruz

playSonuc = playSonuc.astype(float)

model_stats = sm.OLS(playSonuc,X_liste).fit()
model_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.483
Model:                            OLS   Adj. R-squared:                  0.160
Method:                 Least Squares   F-statistic:                     1.493
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.292
Time:                        14:42:31   Log-Likelihood:                -4.9501
No. Observations:                  14   AIC:                             21.90
Df Residuals:                       8   BIC:                             25.73
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.4007      1.859      1.829      0.105      -0.887       7.688
x1            -0.4533      0.351     -1.291      0.233      -1.263       0.357
x2            -0.5814      0.309     -1.883      0.096      -1.293       0.130
x3            -0.4108      0.268     -1.533      0.164      -1.029       0.207
x4            -0.0143      0.025     -0.569      0.585      -0.072       0.044
x5            -0.0142      0.014     -1.031      0.333      -0.046       0.018
==============================================================================
Omnibus:                        0.118   Durbin-Watson:                   1.317
Prob(Omnibus):                  0.943   Jarque-Bera (JB):                0.340
Skew:                           0.035   Prob(JB):                        0.844
Kurtosis:                       2.240   Cond. No.                     1.69e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.69e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
X_liste = np.array(X[:,[0,1,2,3,5]],dtype=float)
model_stats = sm.OLS(playSonuc, X_liste).fit()

model_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.462
Model:                            OLS   Adj. R-squared:                  0.223
Method:                 Least Squares   F-statistic:                     1.931
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.189
Time:                        14:42:31   Log-Likelihood:                -5.2280
No. Observations:                  14   AIC:                             20.46
Df Residuals:                       9   BIC:                             23.65
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.5317      1.021      2.480      0.035       0.222       4.841
x1            -0.3605      0.299     -1.205      0.259      -1.037       0.316
x2            -0.5845      0.297     -1.969      0.080      -1.256       0.087
x3            -0.3586      0.242     -1.481      0.173      -0.906       0.189
x4            -0.0171      0.012     -1.399      0.195      -0.045       0.011
==============================================================================
Omnibus:                        0.557   Durbin-Watson:                   1.461
Prob(Omnibus):                  0.757   Jarque-Bera (JB):                0.554
Skew:                          -0.005   Prob(JB):                        0.758
Kurtosis:                       2.025   Cond. No.                         719.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [17]:
X_liste = np.array(X[:, [0, 2, 3, 5]], dtype=float)

model_stats = sm.OLS(playSonuc,X_liste).fit()
model_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.375
Model:                            OLS   Adj. R-squared:                  0.187
Method:                 Least Squares   F-statistic:                     2.000
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.178
Time:                        14:42:31   Log-Likelihood:                -6.2754
No. Observations:                  14   AIC:                             20.55
Df Residuals:                      10   BIC:                             23.11
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.5232      1.044      2.417      0.036       0.198       4.849
x1            -0.3822      0.250     -1.527      0.158      -0.940       0.175
x2            -0.3449      0.247     -1.395      0.193      -0.896       0.206
x3            -0.0195      0.012     -1.584      0.144      -0.047       0.008
==============================================================================
Omnibus:                        0.600   Durbin-Watson:                   1.569
Prob(Omnibus):                  0.741   Jarque-Bera (JB):                0.408
Skew:                          -0.373   Prob(JB):                        0.815
Kurtosis:                       2.620   Cond. No.                         719.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
X_liste = np.array(X[:, [0, 3, 5]], dtype=float)

model_stats = sm.OLS(playSonuc,X_liste).fit()
model_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.229
Model:                            OLS   Adj. R-squared:                  0.089
Method:                 Least Squares   F-statistic:                     1.635
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.239
Time:                        14:42:31   Log-Likelihood:                -7.7430
No. Observations:                  14   AIC:                             21.49
Df Residuals:                      11   BIC:                             23.40
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.4090      1.102      2.185      0.051      -0.017       4.835
x1            -0.3304      0.262     -1.263      0.233      -0.906       0.246
x2            -0.0199      0.013     -1.523      0.156      -0.049       0.009
==============================================================================
Omnibus:                        0.731   Durbin-Watson:                   1.519
Prob(Omnibus):                  0.694   Jarque-Bera (JB):                0.691
Skew:                          -0.294   Prob(JB):                        0.708
Kurtosis:                       2.084   Cond. No.                         717.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [19]:
X_liste = np.array(X[:,[0,5]],dtype=float)

model_stats = sm.OLS(playSonuc,X_liste).fit()
model_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.117
Model:                            OLS   Adj. R-squared:                  0.044
Method:                 Least Squares   F-statistic:                     1.597
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.230
Time:                        14:42:31   Log-Likelihood:                -8.6904
No. Observations:                  14   AIC:                             21.38
Df Residuals:                      12   BIC:                             22.66
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.9956      1.078      1.851      0.089      -0.354       4.345
x1            -0.0166      0.013     -1.264      0.230      -0.045       0.012
==============================================================================
Omnibus:                        2.744   Durbin-Watson:                   1.600
Prob(Omnibus):                  0.254   Jarque-Bera (JB):                1.417
Skew:                          -0.468   Prob(JB):                        0.492
Kurtosis:                       1.754   Cond. No.                         683.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

from sklearn import preprocessing
veriler2= veriler.apply(preprocessing.LabelEncoder.fit_transform)

* Verilerdeki bütün kategorik verilere tek satırda label encoding uygulama yaptık
* Fakat veriler sütununda kategorik verilerle birlikte sayısal veriler de encode oldu, bu istemediğimiz bir durum.
* Bu yüzden bu kodu kullanmadan önce sayısal verileri ayırmak gerekir.

In [20]:
new_y = sayisalSütunlar[['humidity']]

In [21]:
concatted_df = concatted_df.drop('humidity',axis=1)
x_train,x_test,y_train,y_test = train_test_split(concatted_df,new_y,test_size=0.33,random_state=0)

In [23]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [24]:
y_pred = regressor.predict(x_test)
y_pred

array([[89.09354537],
       [65.86342376],
       [88.52666043],
       [66.08044902],
       [75.05425631]])

In [26]:
import statsmodels.api as sm
X=np.append(arr=np.ones((14,1)).astype(int),values=concatted_df,axis=1)
X_liste = np.array(X[:,[0,1,2,3,4]],dtype=float)

model_stats = sm.OLS(new_y,X_liste).fit()
model_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.200
Model:                            OLS   Adj. R-squared:                 -0.156
Method:                 Least Squares   F-statistic:                    0.5620
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.696
Time:                        14:47:48   Log-Likelihood:                -50.416
No. Observations:                  14   AIC:                             110.8
Df Residuals:                       9   BIC:                             114.0
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         27.4591     44.162      0.622      0.550     -72.442     127.360
x1             7.9270      8.098      0.979      0.353     -10.392      26.246
x2             2.0985      7.454      0.282      0.785     -14.764      18.961
x3            -0.7119      6.496     -0.110      0.915     -15.407      13.983
x4             0.6920      0.566      1.222      0.253      -0.589       1.973
==============================================================================
Omnibus:                        2.785   Durbin-Watson:                   2.568
Prob(Omnibus):                  0.248   Jarque-Bera (JB):                1.463
Skew:                           0.493   Prob(JB):                        0.481
Kurtosis:                       1.761   Cond. No.                     1.11e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.11e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [27]:
X_liste = np.array(X[:,[0,1,2,4]],dtype=float)

model_stats = sm.OLS(new_y,X_liste).fit()
model_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.199
Model:                            OLS   Adj. R-squared:                 -0.042
Method:                 Least Squares   F-statistic:                    0.8270
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.509
Time:                        14:48:22   Log-Likelihood:                -50.425
No. Observations:                  14   AIC:                             108.8
Df Residuals:                      10   BIC:                             111.4
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         25.3137     37.580      0.674      0.516     -58.419     109.047
x1             8.1223      7.499      1.083      0.304      -8.587      24.832
x2             2.1410      7.067      0.303      0.768     -13.605      17.887
x3             0.7158      0.496      1.443      0.180      -0.390       1.821
==============================================================================
Omnibus:                        2.349   Durbin-Watson:                   2.548
Prob(Omnibus):                  0.309   Jarque-Bera (JB):                1.375
Skew:                           0.497   Prob(JB):                        0.503
Kurtosis:                       1.831   Cond. No.                         993.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [28]:
X_liste = np.array(X[:,[0,1,4]],dtype=float)

model_stats = sm.OLS(new_y,X_liste).fit()
model_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.191
Model:                            OLS   Adj. R-squared:                  0.044
Method:                 Least Squares   F-statistic:                     1.302
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.311
Time:                        14:48:51   Log-Likelihood:                -50.489
No. Observations:                  14   AIC:                             107.0
Df Residuals:                      11   BIC:                             108.9
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         25.5448     35.988      0.710      0.493     -53.663     104.753
x1             7.0071      6.258      1.120      0.287      -6.768      20.782
x2             0.7285      0.474      1.538      0.152      -0.314       1.771
==============================================================================
Omnibus:                        2.148   Durbin-Watson:                   2.595
Prob(Omnibus):                  0.342   Jarque-Bera (JB):                1.373
Skew:                           0.531   Prob(JB):                        0.503
Kurtosis:                       1.892   Cond. No.                         993.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [29]:
X_liste = np.array(X[:, [0, 4]], dtype=float)
model_stats = sm.OLS(new_y, X_liste).fit()
print(model_stats.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.099
Model:                            OLS   Adj. R-squared:                  0.024
Method:                 Least Squares   F-statistic:                     1.323
Date:                Sun, 26 Apr 2026   Prob (F-statistic):              0.273
Time:                        14:49:16   Log-Likelihood:                -51.244
No. Observations:                  14   AIC:                             106.5
Df Residuals:                      12   BIC:                             107.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         45.3626     31.663      1.433      0.177     -23.626     114.351
x1             0.4931      0.429      1.150      0.273      -0.441       1.427
==============================================================================
Omnibus:                        2.121   Durbin-Watson:                   2.690
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.064
Skew:                           0.273   Prob(JB):                        0.587
Kurtosis:                       1.765   Cond. No.                         861.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.